version: '3.4'

services:
  next-app:
    image: rodarte/nextjs-fr-pokemon-static-app-dev:abbea69
    environment:
      NEXT_PUBLIC_STAGE: development-docker
      ALLOWED_IMAGE_DOMAINS: raw.githubusercontent.com
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - ./pokemon-static-app:/node/app
      - /node/app/node_modules
